final List<Map<String, dynamic>> tuitionData = const [
  {"major": "Atmospheric Sciences", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Geographic Sciences", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Geology", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Experimental Class of Science", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Electronic Information", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Industrial Engineering", "cat": "Science", "year": 4, "fee": "5,800"},
  {"major": "Automation", "cat": "Science", "year": 4, "fee": "5,800"},
  {"major": "Chemistry", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Environmental Sciences & Engineering", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Computer Science and Technology", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Urban and Rural Planning", "cat": "Science", "year": 5, "fee": "5,800"},
  {"major": "Architecture", "cat": "Science", "year": 4, "fee": "5,800"},
  {"major": "Software Engineering", "cat": "Science", "year": 4, "fee": "6,380*"},
  {"major": "Biological Sciences", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Mathematics", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Astronomy", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Physics", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Material Sciences", "cat": "Science", "year": 4, "fee": "6,050"},
  {"major": "Clinical Medicine", "cat": "Science", "year": 8, "fee": "6,800"},
  {"major": "Clinical Medicine (5+3)", "cat": "Science", "year": 5, "fee": "6,800"},
  {"major": "Law", "cat": "Liberal Arts", "year": 4, "fee": "5,200"},
  {"major": "Teaching Chinese (TCSOL)", "cat": "Liberal Arts", "year": 4, "fee": "5,200"},
  {"major": "History", "cat": "Liberal Arts", "year": 4, "fee": "5,720"},
  {"major": "Korean", "cat": "Liberal Arts", "year": 4, "fee": "5,200"},
  {"major": "German", "cat": "Liberal Arts", "year": 4, "fee": "5,720"},
  {"major": "Russian", "cat": "Liberal Arts", "year": 4, "fee": "5,200"},
  {"major": "French", "cat": "Liberal Arts", "year": 4, "fee": "5,720"},
  {"major": "Japanese", "cat": "Liberal Arts", "year": 4, "fee": "5,200"},
  {"major": "Spanish", "cat": "Liberal Arts", "year": 4, "fee": "5,720"},
  {"major": "English", "cat": "Liberal Arts", "year": 4, "fee": "5,720"},
  {"major": "Chinese Language & Literature", "cat": "Liberal Arts", "year": 4, "fee": "5,720"},
  {"major": "Journalism & Communication", "cat": "Liberal Arts", "year": 4, "fee": "5,200"},
  {"major": "Philosophy", "cat": "Liberal Arts", "year": 4, "fee": "5,720"},
  {"major": "Public Management", "cat": "Liberal Arts", "year": 4, "fee": "5,200"},
  {"major": "Business Administration", "cat": "Mixed", "year": 4, "fee": "5,720"},
  {"major": "Economics", "cat": "Mixed", "year": 4, "fee": "5,720"},
  {"major": "Sociology", "cat": "Mixed", "year": 4, "fee": "5,720"},
  {"major": "Info Management & Systems", "cat": "Mixed", "year": 4, "fee": "5,200"},
];
final List<Map<String, String>> undergraduatePrograms = [
  {"major": "Atmospheric Sciences", "category": "science", "length": "4", "school": "School of Atmospheric Sciences"},
  {"major": "Geographic Sciences", "category": "science", "length": "4", "school": "School of Geographic and Oceanographic Sciences"},
  {"major": "Geology", "category": "science", "length": "4", "school": "School of Earth Sciences and Engineering"},
  {"major": "Experimental Class of Science", "category": "science", "length": "4", "school": "School of Earth Sciences and Engineering, School of Geographic and Oceanographic Sciences, School of Atmospheric Sciences, School of the Environment"},
  {"major": "Electronic Information", "category": "science", "length": "4", "school": "School of Electronic Science and Engineering"},
  {"major": "Industrial Engineering", "category": "science", "length": "4", "school": "School of Management and Engineering"},
  {"major": "Automation", "category": "science", "length": "4", "school": "School of Management and Engineering"},
  {"major": "Chemistry", "category": "science", "length": "4", "school": "School of Chemistry and Chemical Engineering"},
  {"major": "Environmental Sciences and Engineering", "category": "science", "length": "4", "school": "School of the Environment"},
  {"major": "Computer Science and Engineering", "category": "science", "length": "4", "school": "Department of Computer Science and Engineering"},
  {"major": "Urban and Rural Planning", "category": "science", "length": "5", "school": "School of Architecture and Urban Planning"},
  {"major": "Architecture", "category": "science", "length": "4", "school": "School of Architecture and Urban Planning"},
  {"major": "Experimental Class of Science", "category": "science", "length": "4", "school": "Kuang Yaming Honors School"},
  {"major": "Software Engineering", "category": "science", "length": "4", "school": "School of Software Engineering"},
  {"major": "Biological Sciences", "category": "science", "length": "4", "school": "School of Life Sciences"},
  {"major": "Mathematics", "category": "science", "length": "4", "school": "Department of Mathematics"},
  {"major": "Astronomy", "category": "science", "length": "4", "school": "School of Astronomy and Space Sciences"},
  {"major": "Physics", "category": "science", "length": "4", "school": "School of Physics"},
  {"major": "Material Sciences", "category": "science", "length": "4", "school": "School of Engineering and Applied Sciences"},
  {"major": "Clinical Medicine", "category": "science", "length": "8", "school": "Medical School"},
  {"major": "Clinical Medicine (5+3 integration)", "category": "science", "length": "5", "school": "Medical School"},
  {"major": "Law", "category": "liberal arts", "length": "4", "school": "School of Law"},
  {"major": "Teaching Chinese to Speakers of Other Languages", "category": "liberal arts", "length": "4", "school": "Institute for International Students"},
  {"major": "History", "category": "liberal arts", "length": "4", "school": "School of History"},
  {"major": "Korean", "category": "liberal arts", "length": "4", "school": "School of Foreign Studies"},
  {"major": "German", "category": "liberal arts", "length": "4", "school": "School of Foreign Studies"},
  {"major": "Russian", "category": "liberal arts", "length": "4", "school": "School of Foreign Studies"},
  {"major": "French", "category": "liberal arts", "length": "4", "school": "School of Foreign Studies"},
  {"major": "Japanese", "category": "liberal arts", "length": "4", "school": "School of Foreign Studies"},
  {"major": "Spanish", "category": "liberal arts", "length": "4", "school": "School of Foreign Studies"},
  {"major": "English", "category": "liberal arts", "length": "4", "school": "School of Foreign Studies"},
  {"major": "Chinese Language and Literature", "category": "liberal arts", "length": "4", "school": "School of Liberal Arts"},
  {"major": "Journalism and Communication", "category": "liberal arts", "length": "4", "school": "School of Journalism and Communication"},
  {"major": "Philosophy", "category": "liberal arts", "length": "4", "school": "Department of Philosophy"},
  {"major": "Public Management", "category": "liberal arts", "length": "4", "school": "School of Government"},
  {"major": "Business Administration", "category": "liberal arts and science", "length": "4", "school": "School of Business"},
  {"major": "Economics", "category": "liberal arts and science", "length": "4", "school": "School of Business"},
  {"major": "Sociology", "category": "liberal arts and science", "length": "4", "school": "School of Social and Behavioral Sciences"},
  {"major": "Information Management and Information System", "category": "liberal arts and science", "length": "4", "school": "School of Information Management"},
];
final List<Map<String, String>> programs = [
  {"program": "Atmospheric Sciences", "major": "Atmospheric science, applied meteorology", "category": "science", "length": "4"},
  {"program": "Geographic Sciences", "major": "Geographic science, geographic information science, physical geography, resources and the environment, oceanographic science", "category": "science", "length": "4"},
  {"program": "Geology", "major": "Geophysics, geochemistry, geological engineering, water resource and environment, resources and energy, paleontology", "category": "science", "length": "4"},
  {"program": "Science Development Class", "major": "Development class of earth system science and environment", "category": "science", "length": "4"},
  {"program": "Electronic Information", "major": "Electronic information science and technology, communication engineering, medical information engineering, micro-electronics", "category": "science", "length": "4"},
  {"program": "Industrial Engineering", "major": "Financial engineering, industrial engineering", "category": "science", "length": "4"},
  {"program": "Automation", "major": "Automation", "category": "science", "length": "4"},
  {"program": "Chemistry", "major": "Chemistry, applied chemistry, highpolymer science and engineering", "category": "science", "length": "4"},
  {"program": "Environmental Sciences and Engineering", "major": "Environmental engineering, environmental planning and administration, environmental chemistry, environmental biology", "category": "science", "length": "4"},
  {"program": "Computer Science and Technology", "major": "Computer Science and Engineering", "category": "science", "length": "4"},
  {"program": "Urban and Rural Planning", "major": "Urban and Rural Planning", "category": "science", "length": "5"},
  {"program": "Architecture", "major": "Architecture", "category": "science", "length": "4"},
  {"program": "Science Development Class", "major": "Science Development Class", "category": "science", "length": "4"},
  {"program": "Software Engineering", "major": "Software Engineering", "category": "science", "length": "4"},
  {"program": "Biological Sciences", "major": "Biological science, biological technology, ecology", "category": "science", "length": "4"},
  {"program": "Mathematics", "major": "Mathematics and applied mathematics, Information and computational Science, Statistics", "category": "science", "length": "4"},
  {"program": "Astronomy", "major": "Astronomy, space science and technology", "category": "science", "length": "4"},
  {"program": "Physics", "major": "Physics, applied physics, acoustics", "category": "science", "length": "4"},
  {"program": "Material Sciences", "major": "Materials physics, materials chemistry, new energy, optical engineering, biomedical engineering", "category": "science", "length": "4"},
  {"program": "Clinical Medicine", "major": "Clinical Medicine", "category": "science", "length": "8"},
  {"program": "Clinical Medicine (5 + 3 integration)", "major": "Clinical medicine, stomatology", "category": "science", "length": "5"},
  {"program": "Law", "major": "Law", "category": "liberal arts", "length": "4"},
  {"program": "Chinese International Education", "major": "Teaching Chinese to Speakers of Other Languages", "category": "liberal arts", "length": "4"},
  {"program": "History", "major": "History, archeology, cultural relics identification and restoration", "category": "liberal arts", "length": "4"},
  {"program": "Korean", "major": "Korean", "category": "liberal arts", "length": "4"},
  {"program": "German", "major": "German", "category": "liberal arts", "length": "4"},
  {"program": "Russian", "major": "Russian", "category": "liberal arts", "length": "4"},
  {"program": "French", "major": "French", "category": "liberal arts", "length": "4"},
  {"program": "Japanese", "major": "Japanese", "category": "liberal arts", "length": "4"},
  {"program": "Spanish", "major": "Spanish", "category": "liberal arts", "length": "4"},
  {"program": "English", "major": "English", "category": "liberal arts", "length": "4"},
  {"program": "Chinese Language and Literature", "major": "Chinese Language and Literature", "category": "liberal arts", "length": "4"},
  {"program": "Journalism and Communication", "major": "Journalism, advertising, radio and television", "category": "liberal arts", "length": "4"},
  {"program": "Philosophy", "major": "Philosophy", "category": "liberal arts", "length": "4"},
  {"program": "Public Management", "major": "Administration, social security, political science and public administration, international politics", "category": "liberal arts", "length": "4"},
  {"program": "Business Administration", "major": "Business management, human resource, marketing, accounting, financial management, electronic commerce", "category": "Arts and Science", "length": "4"},
  {"program": "Economics", "major": "Economics, finance, international economics and trade, insurance, financial engineering, public finance", "category": "Arts and Science", "length": "4"},
  {"program": "Sociology", "major": "Sociology, social work and social policy, applied psychology", "category": "Arts and Science", "length": "4"},
  {"program": "Information Management and Information System", "major": "Information management and information systems, library science, archival science, editing and publishing", "category": "Arts and Science", "length": "4"},
];
final List<Map<String, String>> graduatePrograms = const [
  {"discipline": "Philosophy", "firstLevel": "Philosophy", "doctoral": "Philosophy of Marxism", "master": "Philosophy of Marxism"},
  {"discipline": "Philosophy", "firstLevel": "Chinese Philosophy", "doctoral": "Chinese Philosophy", "master": "Chinese Philosophy"},
  {"discipline": "Philosophy", "firstLevel": "Foreign Philosophies", "doctoral": "Foreign Philosophies", "master": "Foreign Philosophies"},
  {"discipline": "Philosophy", "firstLevel": "Logic", "doctoral": "Logic", "master": "Logic"},
  {"discipline": "Philosophy", "firstLevel": "Ethics", "doctoral": "Ethics", "master": "Ethics"},
  {"discipline": "Philosophy", "firstLevel": "Science of Religion", "doctoral": "Science of Religion", "master": "Science of Religion"},
  {"discipline": "Philosophy", "firstLevel": "Philosophy of Science and Technology", "doctoral": "Philosophy of Science and Technology", "master": "Philosophy of Science and Technology"},
  {"discipline": "Economics", "firstLevel": "Theoretical Economics", "doctoral": "Political Economy", "master": "Political Economy"},
  {"discipline": "Economics", "firstLevel": "Western Economics", "doctoral": "Political Economics", "master": "Political Economics"},
  {"discipline": "Economics", "firstLevel": "World Economics", "doctoral": "World Economics", "master": "World Economics"},
  {"discipline": "Economics", "firstLevel": "Applied Economics", "doctoral": "Finance (including Insurance)", "master": "National Economics"},
  {"discipline": "Economics", "firstLevel": "Industrial Economics", "doctoral": "Regional Economics", "master": "Regional Economics"},
  {"discipline": "Economics", "firstLevel": "International Trade", "doctoral": "Finance (including Insurance)", "master": "International Trade"},
  {"discipline": "Law", "firstLevel": "Law", "doctoral": "Jurisprudence", "master": "Jurisprudence"},
  {"discipline": "Law", "firstLevel": "Criminal Jurisprudence", "doctoral": "Criminal Jurisprudence", "master": "Legal History"},
  {"discipline": "Law", "firstLevel": "Civil Law and Commercial Law", "doctoral": "Civil Law and Commercial Law", "master": "Civil Law and Commercial Law"},
  {"discipline": "Political Science", "firstLevel": "Political Theory", "doctoral": "Political Theory", "master": "Political Theory"},
  {"discipline": "Political Science", "firstLevel": "International Politics", "doctoral": "Chinese and Foreign Political Institution", "master": "International Relations"},
  {"discipline": "Sociology", "firstLevel": "Sociology", "doctoral": "Sociology", "master": "Sociology"},
  {"discipline": "Sociology", "firstLevel": "Demography", "doctoral": "Demography", "master": "Demography"},
  {"discipline": "Sociology", "firstLevel": "Anthropology", "doctoral": "Anthropology", "master": "Anthropology"},
  {"discipline": "Sociology", "firstLevel": "Social Work", "doctoral": "Social Work", "master": "Social Work"},
  {"discipline": "Marxist Theory", "firstLevel": "Basic Principles of Marxism", "doctoral": "Basic Principles of Marxism", "master": "Basic Principles of Marxism"},
  {"discipline": "Marxist Theory", "firstLevel": "History of Marxism", "doctoral": "History of Marxism", "master": "History of Marxism"},
  {"discipline": "Education", "firstLevel": "Education Science", "doctoral": "Higher Education", "master": "Curriculum and Teaching Methodology"},
  {"discipline": "Education", "firstLevel": "Psychology", "doctoral": "Basic Psychology", "master": "Applied Psychology"},
  {"discipline": "Physical Education", "firstLevel": "Physical Education Training", "doctoral": "Physical Education Training", "master": "Physical Education Training"},
  {"discipline": "Literature", "firstLevel": "Chinese Language and Literature", "doctoral": "Literature and Art", "master": "Literature and Art"},
  {"discipline": "Literature", "firstLevel": "Linguistics and Applied Linguistics", "doctoral": "Linguistics and Applied Linguistics", "master": "Linguistics and Applied Linguistics"},
  {"discipline": "Foreign Language and Literature", "firstLevel": "English Language and Literature", "doctoral": "English Language and Literature", "master": "English Language and Literature"},
  {"discipline": "Foreign Language and Literature", "firstLevel": "Russian Language and Literature", "doctoral": "Russian Language and Literature", "master": "Russian Language and Literature"},
  {"discipline": "Foreign Language and Literature", "firstLevel": "French Language and Literature", "doctoral": "French Language and Literature", "master": "French Language and Literature"},
  {"discipline": "Foreign Language and Literature", "firstLevel": "German Language and Literature", "doctoral": "German Language and Literature", "master": "German Language and Literature"},
  {"discipline": "Foreign Language and Literature", "firstLevel": "Japanese Language and Literature", "doctoral": "Japanese Language and Literature", "master": "Japanese Language and Literature"},
  {"discipline": "Foreign Language and Literature", "firstLevel": "Spanish Language and Literature", "doctoral": "Spanish Language and Literature", "master": "Spanish Language and Literature"},
  {"discipline": "Natural Science", "firstLevel": "Mathematics", "doctoral": "Basic Mathematics", "master": "Basic Mathematics"},
  {"discipline": "Natural Science", "firstLevel": "Physics", "doctoral": "Theoretical Physics", "master": "Theoretical Physics"},
  {"discipline": "Natural Science", "firstLevel": "Chemistry", "doctoral": "Inorganic Chemistry", "master": "Inorganic Chemistry"},
  {"discipline": "Medicine", "firstLevel": "Basic Medicine", "doctoral": "Human Anatomy and Embryology", "master": "Human Anatomy and Embryology"},
  {"discipline": "Engineering", "firstLevel": "Optical Engineering", "doctoral": "Optical Engineering", "master": "Optical Engineering"},
  {"discipline": "Engineering", "firstLevel": "Materials Science and Engineering", "doctoral": "Materials Physics and Chemistry", "master": "Materials Physics and Chemistry"},
  {"discipline": "Engineering", "firstLevel": "Information and Communication Engineering", "doctoral": "Signal and Information Processing", "master": "Communication and Information Systems"},
  {"discipline": "Engineering", "firstLevel": "Computer Science and Technology", "doctoral": "Computer Systematic Science", "master": "Computer Software and Theory"},
  {"discipline": "Medicine", "firstLevel": "Clinical Medicine", "doctoral": "Internal Medicine", "master": "Internal Medicine"},
  {"discipline": "Medicine", "firstLevel": "Surgery", "doctoral": "Surgery", "master": "Surgery"},
  {"discipline": "Management", "firstLevel": "Business Administration", "doctoral": "Accounting", "master": "Accounting"},
  {"discipline": "Management", "firstLevel": "Public Management", "doctoral": "Administration", "master": "Administration"},
  {"discipline": "Library, Information and Archive Management", "firstLevel": "Library Science", "doctoral": "Library Science", "master": "Library Science"},
  {"discipline": "Art", "firstLevel": "Art Theory", "doctoral": "Art Theory", "master": "Art Theory"},
  {"discipline": "Art", "firstLevel": "Fine Arts", "doctoral": "Fine Arts", "master": "Fine Arts"},
  {"discipline": "Art", "firstLevel": "Drama and Film Studies", "doctoral": "Drama and Film Studies", "master": "Drama and Film Studies"},
];
